language: python
python: '3.7'

notifications:
  pushover:
    api_key:
      secure: L9gxUU6w0T+BYSfpP/9a0LSC9bXpRyAuqDJt1NCsuPFaU0BJTams5jK76UC1IL06H64w3DbtYRRPjRYZAyMjyK6MvZTJUJMdyCCQ8/pzHOQbGDK/9k4F0M1ek2VC/GNvLWqclb3IHS4hxaGtnjBgCfGFC8AJ5EwWMD4Xq8KiA/dTU0yWDEcOtHCbI/6GJm4dwCdXb9Zh+we4TscyhCcBMvrz1gio2MfqfBb9RpQCTr3yIRcXtpAkTgS7wWhZYPENUgbbnied+O/Do8O6nG7eGVa8v+mdqc96+3MUTN2Rw8+w8NS+EZE5KZP7RyClZUc9e++QrZBCoW/ei/TKBI/i2ZXyFxULwY+eOjibxVpbMXBAc16Tl27dgcn2HN3UN7hMTvIl/uhH+F6KaAdjFUU3WLNDMuGH1WzZfRer1tVsTrt9YnlGqt3yH+/8k9GDD+oMHkRuKjePsmSEQjFzy5n3qX/TJE8VF2ORG3/t9IjU0H4aRD2pxfZxvULslhhGmMpYwqQ/UAz9CWldmzHbHSSioNk/yrW0tJnQht0L4k5qbGxu/4LS5JT3Hjy02KAVv2OsyKh4hPs47yi+PFcCoquUzCSshhW2NBOJwxj0EDVmiyRkluZcOe+evBaWv0p9kxDITwRv4SBwTuUossvsEIal4GfElCiEBtxv1cE15pbRpWk=
    users:
      - secure: 1ozVk1U2DCz1gnCLTvp2aTqyIJj92Zht891/bjVkAmyn7UL46f8hVWBiWxQ772XvsWHWqurMoJzetcbgroE0NnzQBGNkrDSfgHk+D82CX5vjX/e/hCcLZDAHjkPv+9hgdTPCj5XHIT7t5IPbiWIhF471XtdB5DiI3SXeSB92xtQDJnS+nYChqYY1XyQWJikuphIdFy/4q6QHZPiC4azcq/1tRebaFfKyRmFqc8OgbDkkg790gMhi18SmoINWADtmwiPEhvFX9P6d/Y6IS7X4vP0G/y289jI401iZbu6rrqfKw1bcdDUZpqBAwp327cYnB8mEwDOd15HiOPMP93aKfiiajOA2qQN3s/QrCAXf2MiGAXg66v+uCcZyuXmR6eJsR9+uJajl5+3fe9rCYl3SENUgUktz33KYlp+1F6QhX9OmlFt05F3PrG8Z0Zm1xWAM5Ky2XBJ5Kkg6YPFDoCsXI5xguhGJV0gugJeMLTIdeAvn15Mw0/OoX9jS92vynpGQPnCDMj5j50847lbzYAgw9H6z/8mjuETDJ5KCaKY5g2qzVdM0g0cIo3ecCMUvHg2SrW+JyyKGblJENquHrIHSimTiknKgaG4p9McxCcp8I/JMtdO3pwin1U/2aoBPO77m/Z8kg0duLfTd4eSuc8sZEdwfOjQU0JwHC0G9qKqr0Wk=

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "pascalstehling"
    token:
      secure: "IOz4lonspWHocfUhExotBNhbUtpacNMWqMmtPed2C/uzdNIPAvcu8oBBbfPSPIsKlq48f8nLs/VD2YgEYn4XjcD7+vhX7f0eDWSH+zd+tZ+t57rmsc88bM2ZgcSNnyNjMWwTpGTEb5KslSDUVtJJSMXnmrpVSeERFk8yuDGIW6+5AlwW7o3vdNos1ZZ16qo1VDY622OthzVXU8th58vKU+Svd4uVR8B+UZ2T4Qar0i3rq/rvGjQOWswFf3fcdWD84CLE+h4UPzhBn9j9lPYLgnWQFL63BAbTSZ+1CUyBdfhNcQIi8xmPI+Ea8keUHbBxyIELJHwZ24S4HgDVrccYcyQ0A1cYJB7QXm7OZh2Pp+ArDOvbEYqppC+RSc19NevgJrILuvAjYGdqIr4PeuyBPTfgskrHFwcA5C2HGXowkwbc4jbllDfZ08xE5eB3wqEDCzuHjAO0DypPFLK2Xtf1563s8KMgeGzducLQfokSLjhW7Alc4+OuCSBbHg9v7BahJyZ1m9r4CAq9zB0z4liZurndnTROAQaJ8ejARpACOKjWgcCD/bV7S0PltOYvf2NkeQIORYrZrhcbuvaBKs18uxllK29aN7nertjrBow4PvMY50tbr1QnQNGc7/RNCh2HxI3vBBDYWR0TkEX8jitjdxEs82PX6R00UOm12NOV+ag="

script:
  - python tests.py
  - coverage run tests.py
  - coverage xml
  - pylint modules -r n --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' > pylint_report.txt
  - sonar-scanner